### ISSUE TITLE
算法还起作用吗

### ISSUE THREAD

**Issue by moshuchao** [gonastyle/train_python_robot#2]

**Comment by gonastyle** [comment]
不起作用了


 
---原始邮件---
发件人: "moshuchao"<notifications@github.com>
发送时间: 2019年5月24日(星期五) 下午4:53
收件人: "gonastyle/train_python_robot"<train_python_robot@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [gonastyle/train_python_robot] 算法还起作用吗 (#2)
